server:
  port: 8080
spring:
  profiles:
    active: local
  application:
    name: order-management-service
  config:
    import: optional:configserver:http://localhost:8888
app:
  confi_test: confi_test