server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: cloud-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/service
#          search-locations: file:/Users/panqinzhang/github/fly-spring-cloud/cloud-config/src/main/resources/service